name: Test Branch
on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Self reference action
      # https://github.com/orgs/community/discussions/25194#discussioncomment-3246777
      - name: Pytest coverage comment
        id: coverageComment
        uses: ./
        with:
          pytest-xml-coverage-path: ./data/coverage_1.xml
          # pytest-coverage-path: ./data/pytest-coverage_4.txt
          junitxml-path: ./data/pytest_1.xml

      - name: Check the output coverage
        run: |
          echo "Coverage Report - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
